#!/bin/sh
#
# GPG agent pinentry error fixer
#
# Syntax:
#
#     gpg-agent-pinentry-error-fixer [gpg-agent-conf-path]
#
#
# ## Tracking
#
#   * Command: gpg-agent-pinentry-error-fixer
#   * Version: 1.0.0
#   * Created: 2017-09-12
#   * Updated: 2017-09-14
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -eu
out() { printf %s\\n "$*" ; }; export -f out
err() { >&2 printf %s\\n "$*" ; }; export -f err
die() { >&2 printf %s\\n "$*" ; exit 1 ; }; export -f die

conf=${1:-~/.gnupg/gpg-agent.conf}

[ -r "$conf" ] &&
out "Ok: found GPG agent conf file: $conf" ||
die "Err: cannot find GPG agent conf file: $conf"

prog=$(grep "pinentry-program" "$conf" | awk '{print $2}') 

[ ! -z "$prog" ] &&
out "Ok: found pinentry-program line in conf file: $prog" ||
die "Err: cannot find pinentry-program line in conf file: $conf"

[ -e "$prog" ] &&
out "Ok: found pinentry program: $prog" ||
die "Err: cannot find pinentry program: $prog"

[ -x "$prog" ] &&
out "Ok: pinentry is executable: $prog" ||
die "Err: pinentry program is not executable: $prog"

out "Try gpg now."
out ""
out "If gpg still doesn't work because of pinentry, then try running:"
out ""
out "    gpg-connect-agent reloadagent /bye"
out ""
out "If gpg still doesn't work, then try:
out ""
out "    killall gpg-agent; gpg-agent --daemon --pinentry-program /usr/local/bin/pinentry"


