#!/bin/sh

out() { printf %s\\n "$*" ; }; export -f out
err() { >&2 printf %s\\n "$*" ; }; export -f err
die() { >&2 printf %s\\n "$*" ; exit 1 ; }; export -f die
cmd() { command -v $1 >/dev/null 2>&1 ; }; export -f cmd

conf=~/.gnupg/gpg-agent.conf
[ -r "$conf" ] || die "Err: cannot find conf file: $conf"

prog=$(grep "pinentry-program" "$conf" | awk '{print $2}') 
[ ! -z "$prog" ] || die "Err: cannot find pinentry-program line in conf file: $conf"
[ -e "$prog" ] || die "Err: cannot file pinentry program: $prog"
[ -x "$prog" ] || die "Err: cannot execute pinentry program: $prog"

out "Try gpg now. If gpg still doesn't work because of pinentry, then try:"
out "killall gpg-agent; gpg-agent --daemon --pinentry-program /usr/local/bin/pinentry"
   